# Generated by Django 3.2.12 on 2022-02-20 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eat_advisor_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='restaurant',
            table='restaurants',
        ),
        migrations.AlterModelTable(
            name='review',
            table='reviews',
        ),
    ]
